### ISSUE TITLE
Bad access

### ISSUE THREAD

**Issue by sphings79** [Dablakbandit/always-online#10]
[15:01:56 ERROR]: Error occurred while enabling AlwaysOnline v6.1.6 (Is it up to date?)
java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    com/mojang/authlib/yggdrasil/NMSAuthEnvironmentService.fillGameProfile(Lcom/mojang/authlib/GameProfile;Z)Lcom/mojang/authlib/GameProfile; @6: invokevirtual
  Reason:
    Type 'com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService' (current frame, stack[0]) is not assignable to 'com/mojang/authlib/yggdrasil/NMSAuthEnvironmentService'
  Current Frame:
    bci: @6
    flags: { }
    locals: { 'com/mojang/authlib/yggdrasil/NMSAuthEnvironmentService', 'com/mojang/authlib/GameProfile', integer }
    stack: { 'com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService', 'com/mojang/authlib/GameProfile', integer }
  Bytecode:
    0000000: 2ab4 0002 2b1c b600 26b0               

	at me.johnnywoof.ao.spigot.authservices.NMSAuthSetup.setUp(NMSAuthSetup.java:37) ~[always-online-latest.jar:?]
	at me.johnnywoof.ao.spigot.SpigotLoader.onEnable(SpigotLoader.java:37) ~[always-online-latest.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-214]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-214]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-214]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-214]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-214]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-214]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:01:56 INFO]: [AlwaysOnline] Disabling AlwaysOnline v6.1.6

latest 1.18.1
and your latest from spigot

**Comment by Dablakbandit** [comment]
Can you try the latest?

**Comment by sphings79** [comment]
Sorry forgot to tell you that it's working fine
