### ISSUE TITLE
Exception in VelocityLoader: Expected BEGIN_OBJECT but was STRING

### ISSUE THREAD

**Issue by zefir-git** [Dablakbandit/always-online#13]
Velocity `3.1.2-SNAPSHOT` https://github.com/PaperMC/Velocity/commit/3ae93875 Build 139
Always Online: does not report version, shows `${version}`. In reality it's `6.1.9-RELEASE`

Full stack:
```
[23:34:56 ERROR]: Exception in task me.johnnywoof.ao.velocity.VelocityLoader$$Lambda$1002/0x00000008011f4fe8@3ce84c65 by plugin Always Online
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:944) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at me.johnnywoof.ao.utils.CheckMethods.directSessionServerStatus(CheckMethods.java:33) ~[?:?]
        at me.johnnywoof.ao.hybrid.MojangSessionCheck.run(MojangSessionCheck.java:45) ~[?:?]
        at me.johnnywoof.ao.velocity.VelocityLoader.lambda$runAsyncRepeating$1(VelocityLoader.java:71) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        ... 9 more
[23:35:56 ERROR]: Exception in task me.johnnywoof.ao.velocity.VelocityLoader$$Lambda$1002/0x00000008011f4fe8@3ce84c65 by plugin Always Online
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:944) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at me.johnnywoof.ao.utils.CheckMethods.directSessionServerStatus(CheckMethods.java:33) ~[?:?]
        at me.johnnywoof.ao.hybrid.MojangSessionCheck.run(MojangSessionCheck.java:45) ~[?:?]
        at me.johnnywoof.ao.velocity.VelocityLoader.lambda$runAsyncRepeating$1(VelocityLoader.java:71) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        ... 9 more
[23:36:56 ERROR]: Exception in task me.johnnywoof.ao.velocity.VelocityLoader$$Lambda$1002/0x00000008011f4fe8@3ce84c65 by plugin Always Online
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:944) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at me.johnnywoof.ao.utils.CheckMethods.directSessionServerStatus(CheckMethods.java:33) ~[?:?]
        at me.johnnywoof.ao.hybrid.MojangSessionCheck.run(MojangSessionCheck.java:45) ~[?:?]
        at me.johnnywoof.ao.velocity.VelocityLoader.lambda$runAsyncRepeating$1(VelocityLoader.java:71) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b139)]
        ... 9 more
```

**Comment by Dablakbandit** [comment]
Please make sure your server is able to connect to https://authserver.mojang.com/

**Comment by zefir-git** [comment]
> Please make sure your server is able to connect to https://authserver.mojang.com/

It usually is. I noticed this error randomly in logs without any evident cause. Generally otherwise, the plugin appears to load and function as expected.
