### ISSUE TITLE
Exception disabling plugin AlwaysOnline

### ISSUE THREAD

**Issue by Ceddix** [Dablakbandit/always-online#14]
Hey, I get the following error when I restart the proxy server:
```
[02:15:53] [Shutdown Thread/INFO] [AlwaysOnline]: Saving data...
[02:15:53] [Shutdown Thread/INFO] [AlwaysOnline]: Closing database connections/streams...
[02:15:53] [Shutdown Thread/ERROR]: java.lang.IllegalArgumentException: No task with id 64
[02:15:53] [Shutdown Thread/ERROR]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:193)
[02:15:53] [Shutdown Thread/ERROR]: 	at net.md_5.bungee.scheduler.BungeeScheduler.cancel(BungeeScheduler.java:41)
[02:15:53] [Shutdown Thread/ERROR]: 	at me.johnnywoof.ao.bungee.BungeeLoader.cancelTask(BungeeLoader.java:49)
[02:15:53] [Shutdown Thread/ERROR]: 	at me.johnnywoof.ao.databases.MySQLDatabase.close(MySQLDatabase.java:168)
[02:15:53] [Shutdown Thread/ERROR]: 	at me.johnnywoof.ao.hybrid.AlwaysOnline.disable(AlwaysOnline.java:46)
[02:15:53] [Shutdown Thread/ERROR]: 	at me.johnnywoof.ao.bungee.BungeeLoader.onDisable(BungeeLoader.java:38)
[02:15:53] [Shutdown Thread/ERROR]: 	at net.md_5.bungee.BungeeCord.independentThreadStop(BungeeCord.java:474)
[02:15:53] [Shutdown Thread/ERROR]: 	at net.md_5.bungee.BungeeCord.access$000(BungeeCord.java:100)
[02:15:53] [Shutdown Thread/ERROR]: 	at net.md_5.bungee.BungeeCord$5.run(BungeeCord.java:414)
[02:15:53] [Shutdown Thread/ERROR]: Exception disabling plugin AlwaysOnline
java.lang.IllegalArgumentException: No task with id 66
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:193) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
	at net.md_5.bungee.scheduler.BungeeScheduler.cancel(BungeeScheduler.java:41) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
	at me.johnnywoof.ao.bungee.BungeeLoader.cancelTask(BungeeLoader.java:49) ~[?:?]
	at me.johnnywoof.ao.hybrid.AlwaysOnline.disable(AlwaysOnline.java:52) ~[?:?]
	at me.johnnywoof.ao.bungee.BungeeLoader.onDisable(BungeeLoader.java:38) ~[?:?]
	at net.md_5.bungee.BungeeCord.independentThreadStop(BungeeCord.java:474) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
	at net.md_5.bungee.BungeeCord.access$000(BungeeCord.java:100) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
	at net.md_5.bungee.BungeeCord$5.run(BungeeCord.java:414) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
```

My server version:
![image](https://user-images.githubusercontent.com/49922771/177019984-21a99d10-864b-4e33-9a54-a7f444c2f868.png)

**Comment by Ceddix** [comment]
Seems to be working again. No idea what happened.
