### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by SladeHazard** [Dablakbandit/always-online#21]
MySQL doen't work.. my credentials are correct & the server is latest Velocity

[05:52:19 WARN] [alwaysonline]: Failed to load the MySQL database, falling back to file database.
[05:52:19 ERROR]: java.sql.SQLException: No suitable driver found for jdbc:mysql://172.18.0.1:3306/s45_alwaysonline
[05:52:19 ERROR]:       at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
[05:52:19 ERROR]:       at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
[05:52:19 ERROR]:       at me.dablakbandit.ao.databases.MySQLDatabase.connect(MySQLDatabase.java:57)
[05:52:19 ERROR]:       at me.dablakbandit.ao.databases.MySQLDatabase.<init>(MySQLDatabase.java:38)
[05:52:19 ERROR]:       at me.dablakbandit.ao.hybrid.AlwaysOnline.reload(AlwaysOnline.java:124)
[05:52:19 ERROR]:       at me.dablakbandit.ao.velocity.VelocityLoader.onProxyInitialization(VelocityLoader.java:51)
[05:52:19 ERROR]:       at me.dablakbandit.ao.velocity.Lmbda$10.execute(Unknown Source)
[05:52:19 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[05:52:19 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[05:52:19 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[05:52:19 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[05:52:19 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[05:52:19 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by Dablakbandit** [comment]
Can you try this:
https://github.com/Dablakbandit/always-online/blob/velocity-mysql/output/always-online-latest.jar

Changes:
https://github.com/Dablakbandit/always-online/commit/3f5f954ce0725c3f133411e20c8e10e6bc6fe3d1

**Comment by SladeHazard** [comment]
works ty
