### ISSUE TITLE
Won't work with Floodgate/Geyser

### ISSUE THREAD

**Issue by sphings79** [Dablakbandit/always-online#9]
Users will get disconnected if they join with bedrock.

`[15:52:20 INFO]: [Geyser-Spigot] /46.83.190.185:55712 tried to connect!
[15:52:20 INFO]: [Geyser-Spigot] Player connected with username ZuluBueffel4602
[15:52:20 INFO]: [Geyser-Spigot] ZuluBueffel4602 (logged in as: ZuluBueffel4602) has connected to the Java server
[15:52:20 WARN]: java.lang.reflect.InvocationTargetException
[15:52:20 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:20 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[15:52:20 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:20 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:52:20 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.checkAndHandleLogin(SpigotDataHandler.java:169)
[15:52:20 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:118)
[15:52:20 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:52:20 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[15:52:20 WARN]: 	at ClientDetector.jar//de.sportkanone123.clientdetector.spigot.packetevents.injector.modern.PlayerChannelHandlerModern.channelRead(PlayerChannelHandlerModern.java:39)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:52:20 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:52:20 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[15:52:20 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:52:20 WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[15:52:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
[15:52:20 WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[15:52:20 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[15:52:20 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:52:20 WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:52:20 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:52:20 WARN]: Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[15:52:20 WARN]: 	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
[15:52:20 WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200)
[15:52:20 WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187)
[15:52:20 WARN]: 	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:191)
[15:52:20 WARN]: 	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:184)
[15:52:20 WARN]: 	at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:398)
[15:52:20 WARN]: 	... 33 more
[15:52:20 INFO]: [floodgate] Floodgate player logged in as *ZuluBueffel4602 disconnected
[15:52:20 INFO]: [Geyser-Spigot] ZuluBueffel4602 has disconnected from the Java server because of Connection closed.
[15:52:20 INFO]: com.mojang.authlib.GameProfile@3e87ca16[id=00000000-0000-0000-0009-01f6eae7f8d0,name=*ZuluBueffel4602,properties={},legacy=false] (/46.83.190.185:0) lost connection: Disconnected
[15:52:20 INFO]: [Geyser-Spigot] Bedrock user with ip: /46.83.190.185 has disconnected for reason CLOSED_BY_REMOTE_PEER`

[16:54:49 INFO]: Checking version, please wait...
[16:54:50 INFO]: This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
You are running the latest version
Previous version: git-Paper-186 (MC: 1.18.1)

Your latest Plugin from Spigot.
Geyser/Floodgate latest builds

**Comment by sphings79** [comment]
Additional information from geyser/floodgate devs:
AlwaysOnline needs to fix an issue on their end where they don't call a Paper event. The reason it breaks now is not our fault; Mojang changed an API response on their end.

**Comment by Dablakbandit** [comment]
Can you try with the latest release?

**Comment by sphings79** [comment]
seems to work fine
